import { describe, expect, it } from 'vitest'

import {
  BREAKPOINTS,
  COLOR_FAMILIES,
  COLOR_USAGE,
  DEFAULT_SIZE_NAME,
  DEFAULT_THEME_MODE,
  DEFAULT_THEME_NAME,
  DEFAULT_TRANSITION_DURATION,
  DIALOG_SETTINGS_WIDTH_PX,
  FONT_SCALE_RATIOS,
  LAYOUT_DIMENSION_KEYS,
  SIZE_BASE_VAR_KEYS,
  SIZE_PRESETS,
  SIZE_SCALE_KEYS,
  SIZE_SCALE_MATRIX,
  SORTED_BREAKPOINTS,
  SPACING_SCALE_RATIOS,
  THEME_ENGINE,
  THEME_PRESETS,
  TRANSITION_DURATION_OPTIONS,
  getPresetPrimaryColor,
  resolveBreakpointFromWidth,
} from './index.js'
import {
  BREAKPOINTS as BREAKPOINTS_SOURCE,
  TABLET_DETECTION_MIN_SHORT_SIDE,
} from './breakpoints.js'
import { COLOR_USAGE as COLOR_USAGE_SOURCE } from './colorUsage.js'
import {
  COLOR_FAMILIES as COLOR_FAMILIES_SOURCE,
  THEME_ENGINE as THEME_ENGINE_SOURCE,
} from './metadata.js'
import {
  DEFAULT_SIZE_NAME as DEFAULT_SIZE_NAME_SOURCE,
  DIALOG_SETTINGS_WIDTH_PX as DIALOG_SETTINGS_WIDTH_PX_SOURCE,
  LAYOUT_DIMENSION_KEYS as LAYOUT_DIMENSION_KEYS_SOURCE,
  SIZE_BASE_VAR_KEYS as SIZE_BASE_VAR_KEYS_SOURCE,
  SIZE_PRESETS as SIZE_PRESETS_SOURCE,
} from './size.js'
import {
  FONT_SCALE_RATIOS as FONT_SCALE_RATIOS_SOURCE,
  SIZE_SCALE_KEYS as SIZE_SCALE_KEYS_SOURCE,
  SIZE_SCALE_MATRIX as SIZE_SCALE_MATRIX_SOURCE,
  SPACING_SCALE_RATIOS as SPACING_SCALE_RATIOS_SOURCE,
} from './sizeScale.js'
import {
  DEFAULT_THEME_MODE as DEFAULT_THEME_MODE_SOURCE,
  DEFAULT_THEME_NAME as DEFAULT_THEME_NAME_SOURCE,
  DEFAULT_TRANSITION_DURATION as DEFAULT_TRANSITION_DURATION_SOURCE,
  THEME_PRESETS as THEME_PRESETS_SOURCE,
  TRANSITION_DURATION_OPTIONS as TRANSITION_DURATION_OPTIONS_SOURCE,
  getPresetPrimaryColor as getPresetPrimaryColorSource,
} from './theme.js'
import {
  SORTED_BREAKPOINTS as SORTED_BREAKPOINTS_SOURCE,
  resolveBreakpointFromWidth as resolveBreakpointFromWidthSource,
} from './deviceResolver.js'

describe('@ccd/design-tokens root exports', () => {
  it('re-exports theme and color token data from the canonical modules', () => {
    expect(THEME_PRESETS).toBe(THEME_PRESETS_SOURCE)
    expect(DEFAULT_THEME_NAME).toBe(DEFAULT_THEME_NAME_SOURCE)
    expect(DEFAULT_THEME_MODE).toBe(DEFAULT_THEME_MODE_SOURCE)
    expect(DEFAULT_TRANSITION_DURATION).toBe(DEFAULT_TRANSITION_DURATION_SOURCE)
    expect(TRANSITION_DURATION_OPTIONS).toBe(TRANSITION_DURATION_OPTIONS_SOURCE)
    expect(getPresetPrimaryColor).toBe(getPresetPrimaryColorSource)
    expect(COLOR_FAMILIES).toBe(COLOR_FAMILIES_SOURCE)
    expect(THEME_ENGINE).toBe(THEME_ENGINE_SOURCE)
    expect(COLOR_USAGE).toBe(COLOR_USAGE_SOURCE)
  })

  it('re-exports spacing, breakpoint, and responsive primitives from the canonical modules', () => {
    expect(SIZE_SCALE_KEYS).toBe(SIZE_SCALE_KEYS_SOURCE)
    expect(SIZE_SCALE_MATRIX).toBe(SIZE_SCALE_MATRIX_SOURCE)
    expect(FONT_SCALE_RATIOS).toBe(FONT_SCALE_RATIOS_SOURCE)
    expect(SPACING_SCALE_RATIOS).toBe(SPACING_SCALE_RATIOS_SOURCE)
    expect(SIZE_PRESETS).toBe(SIZE_PRESETS_SOURCE)
    expect(DEFAULT_SIZE_NAME).toBe(DEFAULT_SIZE_NAME_SOURCE)
    expect(LAYOUT_DIMENSION_KEYS).toBe(LAYOUT_DIMENSION_KEYS_SOURCE)
    expect(SIZE_BASE_VAR_KEYS).toBe(SIZE_BASE_VAR_KEYS_SOURCE)
    expect(DIALOG_SETTINGS_WIDTH_PX).toBe(DIALOG_SETTINGS_WIDTH_PX_SOURCE)
    expect(BREAKPOINTS).toBe(BREAKPOINTS_SOURCE)
    expect(SORTED_BREAKPOINTS).toBe(SORTED_BREAKPOINTS_SOURCE)
    expect(resolveBreakpointFromWidth).toBe(resolveBreakpointFromWidthSource)
    expect(TABLET_DETECTION_MIN_SHORT_SIDE).toBe(600)
  })
})
