import type { CompleteThemePreset, ThemePreset, ThemeTransitionDuration } from './types'

/**
 * 核心主题预设池 (全状态极致定制版 - The Ultimate 11)
 * * 核心设计理念：
 * 1. 彻底绕过引擎的自动计算，为每一个主题的 Light/Dark 模式显式指定所有状态色。
 * 2. WCAG 严格对比度：深色背景必配白字 (#ffffff)，亮色背景必配极深色字。
 * 3. 色相融合 (Hue Harmony)：状态色不再是干巴巴的纯红纯绿，而是根据主色调做了冷暖偏移。
 */
export const THEME_PRESETS: CompleteThemePreset[] = [
  // =========================================================================
  // 1. Morandi Elegance (Optimized)
  // =========================================================================
  {
    name: 'morandi-elegance',
    colors: {
      light: {
        background: '#F0F2F5',
        foreground: '#333333',
        neutral: {
          base: '#E0E2E5',
          // DS-SURFACE-01: card/popover raised above the page so panels float; cool near-white keeps the morandi hue.
          bg: '#FEFFFF',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#E9ECEF',
        secondaryForeground: '#333333',
        muted: '#F8F9FA',
        mutedForeground: '#868E96',
        border: '#E0E2E5',
        input: '#DEE2E6',
        ring: '#3A6F9B',
        primary: {
          default: '#3A6F9B',
          foreground: '#F8FAFC',
          hover: '#315F85',
          light: '#7AA0C6',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#8A2BE2',
          foreground: '#FFFFFF',
          hover: '#7A24CC',
          light: '#B266FF',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#6F42C1',
          foreground: '#FFFFFF',
          hover: '#5F38A3',
          light: '#9B7EDD',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#427AA9',
          primaryForeground: '#FFFFFF',
          accent: '#8A2BE2',
          accentForeground: '#FFFFFF',
          border: '#E0E2E5',
          ring: '#4682B4',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#3A6F9B',
        primary: {
          default: '#3A6F9B',
          foreground: '#F8FAFC',
          hover: '#5A9BDC',
          light: '#2A4E6C',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#B266FF',
          foreground: '#111111',
          hover: '#C999FF',
          light: '#6A3EB4',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#6F42C1',
          foreground: '#FFFFFF',
          hover: '#9B7EDD',
          light: '#462A7A',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#3A6F9B',
          primaryForeground: '#F8FAFC',
          accent: '#B266FF',
          accentForeground: '#111111',
          border: '#495057',
          ring: '#4682B4',
        },
      },
    },
  },

  // =========================================================================
  // 2. Soft Morandi Pastels (Optimized)
  // =========================================================================
  {
    name: 'soft-morandi-pastels',
    colors: {
      light: {
        background: '#F8F0F0',
        foreground: '#333333',
        neutral: {
          // Card/popover surface raised toward white so panels, cards, table shells,
          // and popovers float clearly above the warm-rose page (DS-SURFACE-01).
          // Kept just below the #FFFFFF sidebar so it stays a distinct token.
          base: '#EFE0E0',
          bg: '#FEFEFE',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#F5EBEB',
        secondaryForeground: '#333333',
        // Recessed "muted" fill (wells/code blocks) sits a distinct step below the card
        // surface instead of collapsing onto it; stays >= 3:1 against muted-foreground.
        muted: '#FBF6F6',
        mutedForeground: '#868E96',
        border: '#EFE0E0',
        input: '#F2E6E6',
        ring: '#6A5ACD',
        primary: {
          default: '#6A5ACD',
          foreground: '#FFFFFF',
          hover: '#5E4FBC',
          light: '#9388E0',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#20B2AA',
          foreground: '#333333',
          hover: '#1C9A94',
          light: '#66CDAA',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#8A2BE2',
          foreground: '#FFFFFF',
          hover: '#7A24CC',
          light: '#B266FF',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#6A5ACD',
          primaryForeground: '#FFFFFF',
          accent: '#20B2AA',
          accentForeground: '#333333',
          border: '#EFE0E0',
          ring: '#6A5ACD',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#6A5ACD',
        primary: {
          default: '#6A5ACD',
          foreground: '#FFFFFF',
          hover: '#7B6FE0',
          light: '#423782',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#66CDAA',
          foreground: '#333333',
          hover: '#80E0C0',
          light: '#146E6A',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#8A2BE2',
          foreground: '#FFFFFF',
          hover: '#B266FF',
          light: '#5A1A8A',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#6A5ACD',
          primaryForeground: '#FFFFFF',
          accent: '#66CDAA',
          accentForeground: '#333333',
          border: '#495057',
          ring: '#6A5ACD',
        },
      },
    },
  },

  // =========================================================================
  // 3. Modern Calm Neutrals + Warm Accents (Optimized)
  // =========================================================================
  {
    name: 'modern-calm-neutrals',
    colors: {
      light: {
        background: '#FDF7F0',
        foreground: '#333333',
        neutral: {
          base: '#EFE5D9',
          // DS-SURFACE-01: card/popover raised; warm near-white keeps the cream hue, distinct from page + muted.
          bg: '#FFFEFC',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#F8F0E5',
        secondaryForeground: '#333333',
        muted: '#FFFBF5',
        mutedForeground: '#868E96',
        border: '#EFE5D9',
        input: '#F2EBDD',
        ring: '#A85418',
        primary: {
          default: '#A85418',
          foreground: '#FFF7ED',
          hover: '#8A4213',
          light: '#E08D5E',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#2E8B57',
          foreground: '#000000',
          hover: '#287A4B',
          light: '#66CDAA',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#8B4513',
          foreground: '#FFFFFF',
          hover: '#7A3D10',
          light: '#B06F3A',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#B95C1A',
          primaryForeground: '#FFFFFF',
          accent: '#2E8B57',
          accentForeground: '#000000',
          border: '#EFE5D9',
          ring: '#D2691E',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#A85418',
        primary: {
          default: '#A85418',
          foreground: '#FFF7ED',
          hover: '#E08D5E',
          light: '#8A4213',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#66CDAA',
          foreground: '#333333',
          hover: '#80E0C0',
          light: '#1C5A38',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#8B4513',
          foreground: '#FFFFFF',
          hover: '#B06F3A',
          light: '#5A2D0C',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#A85418',
          primaryForeground: '#FFF7ED',
          accent: '#66CDAA',
          accentForeground: '#333333',
          border: '#495057',
          ring: '#D2691E',
        },
      },
    },
  },

  // =========================================================================
  // 4. Eco/Nature-Inspired Earth Tones (Optimized)
  // =========================================================================
  {
    name: 'eco-nature-earth',
    colors: {
      light: {
        background: '#F5F5DC',
        foreground: '#333333',
        neutral: {
          base: '#E8E8D0',
          // DS-SURFACE-01: card/popover raised; warm near-white keeps the eco beige hue.
          bg: '#FEFEF8',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#F0F0E5',
        secondaryForeground: '#333333',
        // DS-SURFACE-01: eco card sits very high, so recess muted into a distinct beige well (stays >= 3:1 vs muted-fg).
        muted: '#FAFAF2',
        mutedForeground: '#868E96',
        border: '#E8E8D0',
        input: '#EFEFD8',
        ring: '#8B4513',
        primary: {
          default: '#8B4513',
          foreground: '#FFFFFF',
          hover: '#7A3D10',
          light: '#B06F3A',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#228B22',
          foreground: '#000000',
          hover: '#1E7A1E',
          light: '#66CDAA',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#A0522D',
          foreground: '#FFFFFF',
          hover: '#8A4628',
          light: '#C07D5A',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#8B4513',
          primaryForeground: '#FFFFFF',
          accent: '#228B22',
          accentForeground: '#000000',
          border: '#E8E8D0',
          ring: '#8B4513',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#8B4513',
        primary: {
          default: '#8B4513',
          foreground: '#FFFFFF',
          hover: '#B06F3A',
          light: '#5A2D0C',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#66CDAA',
          foreground: '#333333',
          hover: '#80E0C0',
          light: '#1C5A1C',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#A0522D',
          foreground: '#FFFFFF',
          hover: '#C07D5A',
          light: '#66341C',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#8B4513',
          primaryForeground: '#FFFFFF',
          accent: '#66CDAA',
          accentForeground: '#333333',
          border: '#495057',
          ring: '#8B4513',
        },
      },
    },
  },

  // =========================================================================
  // 5. Soft Digital Pastels / Elevated Morandi (Optimized)
  // =========================================================================
  {
    name: 'elevated-digital-pastels',
    colors: {
      light: {
        background: '#E0F2F7',
        foreground: '#333333',
        neutral: {
          base: '#D0E6EB',
          // DS-SURFACE-01: card/popover raised; cyan near-white keeps the digital-pastel hue.
          bg: '#FCFEFF',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#E6F0F4',
        secondaryForeground: '#333333',
        muted: '#F0F8FA',
        mutedForeground: '#868E96',
        border: '#D0E6EB',
        input: '#D8EBF0',
        ring: '#006AD5',
        primary: {
          default: '#006AD5',
          foreground: '#F8FAFC',
          hover: '#005AB8',
          light: '#3399FF',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#FF4500',
          foreground: '#111111',
          hover: '#E03E00',
          light: '#FF7033',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#607D8B',
          foreground: '#000000',
          hover: '#455A64',
          light: '#B0BEC5',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#0071EB',
          primaryForeground: '#FFFFFF',
          accent: '#FF4500',
          accentForeground: '#111111',
          border: '#D0E6EB',
          ring: '#007BFF',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#006AD5',
        primary: {
          default: '#006AD5',
          foreground: '#F8FAFC',
          hover: '#3399FF',
          light: '#004A80',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#FF7033',
          foreground: '#333333',
          hover: '#FF9966',
          light: '#A02A00',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#607D8B',
          foreground: '#000000',
          hover: '#B0BEC5',
          light: '#3A4C5A',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#006AD5',
          primaryForeground: '#F8FAFC',
          accent: '#FF7033',
          accentForeground: '#333333',
          border: '#495057',
          ring: '#007BFF',
        },
      },
    },
  },

  // =========================================================================
  // 6. Warm Modern UI / Sunset Accents (Optimized)
  // =========================================================================
  {
    name: 'warm-modern-sunset',
    colors: {
      light: {
        background: '#FFF8E1',
        foreground: '#333333',
        neutral: {
          base: '#F5EED5',
          // DS-SURFACE-01: card/popover raised; warm near-white keeps the sunset hue.
          bg: '#FFFEFB',
          foreground: '#333333',
          secondaryForeground: '#6C757D',
          mutedForeground: '#868E96',
        },
        secondary: '#FDF5E6',
        secondaryForeground: '#333333',
        muted: '#FFFCEF',
        mutedForeground: '#868E96',
        border: '#F5EED5',
        input: '#F8F2E0',
        ring: '#974F16',
        primary: {
          default: '#974F16',
          foreground: '#FFF7ED',
          hover: '#7A3F12',
          light: '#F0A56B',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#27AE60',
          foreground: '#111111',
          hover: '#229954',
          light: '#66CDAA',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#218838',
          light: '#6FD07C',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#138496',
          light: '#5BC0DE',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#333333',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#C82333',
          light: '#EF5350',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#A0522D',
          foreground: '#FFFFFF',
          hover: '#8A4628',
          light: '#C07D5A',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#FFFFFF',
          foreground: '#333333',
          primary: '#974F16',
          primaryForeground: '#FFFFFF',
          accent: '#27AE60',
          accentForeground: '#111111',
          border: '#F5EED5',
          ring: '#E67E22',
        },
      },
      dark: {
        background: '#212529',
        foreground: '#F8F9FA',
        neutral: {
          base: '#495057',
          bg: '#343A40',
          foreground: '#F8F9FA',
          secondaryForeground: '#CED4DA',
          mutedForeground: '#ADB5BD',
        },
        secondary: '#343A40',
        secondaryForeground: '#F8F9FA',
        muted: '#2C3034',
        mutedForeground: '#ADB5BD',
        border: '#495057',
        input: '#6C757D',
        ring: '#974F16',
        primary: {
          default: '#974F16',
          foreground: '#FFF7ED',
          hover: '#F0A56B',
          light: '#914F16',
          lightForeground: '#F8F9FA',
        },
        accent: {
          default: '#66CDAA',
          foreground: '#333333',
          hover: '#80E0C0',
          light: '#1A6B3D',
          lightForeground: '#F8F9FA',
        },
        success: {
          default: '#28A745',
          foreground: '#111111',
          hover: '#34D058',
          light: '#1A6B2D',
          lightForeground: '#F8F9FA',
        },
        info: {
          default: '#17A2B8',
          foreground: '#111111',
          hover: '#20C997',
          light: '#0F6B78',
          lightForeground: '#F8F9FA',
        },
        warn: {
          default: '#FFC107',
          foreground: '#333333',
          hover: '#FFD54F',
          light: '#A08000',
          lightForeground: '#F8F9FA',
        },
        danger: {
          default: '#DC3545',
          foreground: '#FFFFFF',
          hover: '#EF5350',
          light: '#8A212B',
          lightForeground: '#F8F9FA',
        },
        help: {
          default: '#A0522D',
          foreground: '#FFFFFF',
          hover: '#C07D5A',
          light: '#66341C',
          lightForeground: '#F8F9FA',
        },
        sidebar: {
          background: '#343A40',
          foreground: '#F8F9FA',
          primary: '#974F16',
          primaryForeground: '#FFF7ED',
          accent: '#66CDAA',
          accentForeground: '#333333',
          border: '#495057',
          ring: '#E67E22',
        },
      },
    },
  },
  // =========================================================================
  // 7. Royal Amethyst (Purple Series)
  // =========================================================================
  {
    name: 'royal-amethyst',
    colors: {
      light: {
        background: '#F8F0FC',
        foreground: '#2A0A3A',
        neutral: {
          base: '#E6D9ED',
          bg: '#FDF9FF',
          foreground: '#2A0A3A',
          secondaryForeground: '#6A3A8A',
          mutedForeground: '#8A5A9A',
        },
        secondary: '#F2E8F7',
        secondaryForeground: '#2A0A3A',
        muted: '#FBF5FF',
        mutedForeground: '#8A5A9A',
        border: '#E6D9ED',
        input: '#EDE0F2',
        ring: '#8A00FF',
        primary: {
          default: '#8A00FF',
          foreground: '#FFFFFF',
          hover: '#7B00E0',
          light: '#A333FF',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#C9A0FF',
          foreground: '#2A0A3A',
          hover: '#B28AE0',
          light: '#DDC9FF',
          lightForeground: '#2A0A3A',
        },
        success: {
          default: '#4CAF50',
          foreground: '#333333',
          hover: '#439B47',
          light: '#6CC470',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#2196F3',
          foreground: '#111111',
          hover: '#1976D2',
          light: '#64B5F6',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#2A0A3A',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#2A0A3A',
        },
        danger: {
          default: '#F44336',
          foreground: '#111111',
          hover: '#D32F2F',
          light: '#EF9A9A',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#9C27B0',
          foreground: '#FFFFFF',
          hover: '#7B1FA2',
          light: '#CE93D8',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#F8F0FC',
          foreground: '#2A0A3A',
          primary: '#8A00FF',
          primaryForeground: '#FFFFFF',
          accent: '#C9A0FF',
          accentForeground: '#2A0A3A',
          border: '#E6D9ED',
          ring: '#8A00FF',
        },
      },
      dark: {
        background: '#1A052A',
        foreground: '#F0E0FF',
        neutral: {
          base: '#4A2A5A',
          bg: '#3A1A4A',
          foreground: '#F0E0FF',
          secondaryForeground: '#B080D0',
          mutedForeground: '#8050A0',
        },
        secondary: '#3A1A4A',
        secondaryForeground: '#F0E0FF',
        muted: '#2A0A3A',
        mutedForeground: '#FFFFFF',
        border: '#4A2A5A',
        input: '#6A3A8A',
        ring: '#8A00FF',
        primary: {
          default: '#8A00FF',
          foreground: '#FFFFFF',
          hover: '#A333FF',
          light: '#5A00A0',
          lightForeground: '#F0E0FF',
        },
        accent: {
          default: '#C9A0FF',
          foreground: '#2A0A3A',
          hover: '#DDC9FF',
          light: '#7A50A0',
          lightForeground: '#F0E0FF',
        },
        success: {
          default: '#6CC470',
          foreground: '#2A0A3A',
          hover: '#4CAF50',
          light: '#3A7A3A',
          lightForeground: '#F0E0FF',
        },
        info: {
          default: '#64B5F6',
          foreground: '#2A0A3A',
          hover: '#2196F3',
          light: '#3A6A8A',
          lightForeground: '#F0E0FF',
        },
        warn: {
          default: '#FFD54F',
          foreground: '#2A0A3A',
          hover: '#FFC107',
          light: '#A0803A',
          lightForeground: '#F0E0FF',
        },
        danger: {
          default: '#EF9A9A',
          foreground: '#2A0A3A',
          hover: '#F44336',
          light: '#A05050',
          lightForeground: '#F0E0FF',
        },
        help: {
          default: '#CE93D8',
          foreground: '#2A0A3A',
          hover: '#9C27B0',
          light: '#6A3A7A',
          lightForeground: '#F0E0FF',
        },
        sidebar: {
          background: '#3A1A4A',
          foreground: '#F0E0FF',
          primary: '#8A00FF',
          primaryForeground: '#FFFFFF',
          accent: '#C9A0FF',
          accentForeground: '#2A0A3A',
          border: '#4A2A5A',
          ring: '#8A00FF',
        },
      },
    },
  },

  // =========================================================================
  // 8. Emerald Forest (Green Series)
  // =========================================================================
  {
    name: 'emerald-forest',
    colors: {
      light: {
        background: '#F0F8F0',
        foreground: '#0A2A0A',
        neutral: {
          base: '#D9EDD9',
          bg: '#F9FFF9',
          foreground: '#0A2A0A',
          secondaryForeground: '#3A6A3A',
          mutedForeground: '#5A8A5A',
        },
        secondary: '#E8F7E8',
        secondaryForeground: '#0A2A0A',
        muted: '#F5FFF5',
        mutedForeground: '#5A8A5A',
        border: '#D9EDD9',
        input: '#E0F2E0',
        ring: '#008A00',
        primary: {
          default: '#008A00',
          foreground: '#FFFFFF',
          hover: '#007B00',
          light: '#33A333',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#A0FFA0',
          foreground: '#0A2A0A',
          hover: '#8AE08A',
          light: '#C9FFC9',
          lightForeground: '#0A2A0A',
        },
        success: {
          default: '#4CAF50',
          foreground: '#333333',
          hover: '#439B47',
          light: '#6CC470',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#2196F3',
          foreground: '#111111',
          hover: '#1976D2',
          light: '#64B5F6',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#0A2A0A',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#0A2A0A',
        },
        danger: {
          default: '#F44336',
          foreground: '#111111',
          hover: '#D32F2F',
          light: '#EF9A9A',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#8BC34A',
          foreground: '#333333',
          hover: '#689F38',
          light: '#C5E1A5',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#F0F8F0',
          foreground: '#0A2A0A',
          primary: '#008A00',
          primaryForeground: '#FFFFFF',
          accent: '#A0FFA0',
          accentForeground: '#0A2A0A',
          border: '#D9EDD9',
          ring: '#008A00',
        },
      },
      dark: {
        background: '#052A05',
        foreground: '#E0FFE0',
        neutral: {
          base: '#2A4A2A',
          bg: '#1A3A1A',
          foreground: '#E0FFE0',
          secondaryForeground: '#80B080',
          mutedForeground: '#50A050',
        },
        secondary: '#1A3A1A',
        secondaryForeground: '#E0FFE0',
        muted: '#0A2A0A',
        mutedForeground: '#50A050',
        border: '#2A4A2A',
        input: '#3A6A3A',
        ring: '#008A00',
        primary: {
          default: '#008A00',
          foreground: '#FFFFFF',
          hover: '#33A333',
          light: '#005A00',
          lightForeground: '#E0FFE0',
        },
        accent: {
          default: '#A0FFA0',
          foreground: '#0A2A0A',
          hover: '#C9FFC9',
          light: '#50A050',
          lightForeground: '#E0FFE0',
        },
        success: {
          default: '#6CC470',
          foreground: '#0A2A0A',
          hover: '#4CAF50',
          light: '#3A7A3A',
          lightForeground: '#E0FFE0',
        },
        info: {
          default: '#64B5F6',
          foreground: '#0A2A0A',
          hover: '#2196F3',
          light: '#3A6A8A',
          lightForeground: '#E0FFE0',
        },
        warn: {
          default: '#FFD54F',
          foreground: '#0A2A0A',
          hover: '#FFC107',
          light: '#A0803A',
          lightForeground: '#E0FFE0',
        },
        danger: {
          default: '#EF9A9A',
          foreground: '#0A2A0A',
          hover: '#F44336',
          light: '#A05050',
          lightForeground: '#E0FFE0',
        },
        help: {
          default: '#C5E1A5',
          foreground: '#0A2A0A',
          hover: '#8BC34A',
          light: '#5A7A3A',
          lightForeground: '#E0FFE0',
        },
        sidebar: {
          background: '#1A3A1A',
          foreground: '#E0FFE0',
          primary: '#008A00',
          primaryForeground: '#FFFFFF',
          accent: '#A0FFA0',
          accentForeground: '#0A2A0A',
          border: '#2A4A2A',
          ring: '#008A00',
        },
      },
    },
  },

  // =========================================================================
  // 9. Midnight Deep Sea (Dark Blue Series)
  // =========================================================================
  {
    name: 'midnight-deep-sea',
    colors: {
      light: {
        background: '#F0F4F8',
        foreground: '#0A1A2A',
        neutral: {
          base: '#D9E3ED',
          bg: '#F9FBFF',
          foreground: '#0A1A2A',
          secondaryForeground: '#3A5A6A',
          mutedForeground: '#5A7A8A',
        },
        secondary: '#E8F0F7',
        secondaryForeground: '#0A1A2A',
        muted: '#F5F8FF',
        mutedForeground: '#5A7A8A',
        border: '#D9E3ED',
        input: '#E0E7F2',
        ring: '#005A8A',
        primary: {
          default: '#005A8A',
          foreground: '#FFFFFF',
          hover: '#004F7B',
          light: '#337AA3',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#FFD700',
          foreground: '#0A1A2A',
          hover: '#E0B800',
          light: '#FFE066',
          lightForeground: '#0A1A2A',
        },
        success: {
          default: '#4CAF50',
          foreground: '#333333',
          hover: '#439B47',
          light: '#6CC470',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#2196F3',
          foreground: '#111111',
          hover: '#1976D2',
          light: '#64B5F6',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#0A1A2A',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#0A1A2A',
        },
        danger: {
          default: '#F44336',
          foreground: '#111111',
          hover: '#D32F2F',
          light: '#EF9A9A',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#607D8B',
          foreground: '#000000',
          hover: '#455A64',
          light: '#B0BEC5',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#F0F4F8',
          foreground: '#0A1A2A',
          primary: '#005A8A',
          primaryForeground: '#FFFFFF',
          accent: '#FFD700',
          accentForeground: '#0A1A2A',
          border: '#D9E3ED',
          ring: '#005A8A',
        },
      },
      dark: {
        background: '#05101A',
        foreground: '#E0F0FF',
        neutral: {
          base: '#2A3A4A',
          bg: '#1A2A3A',
          foreground: '#E0F0FF',
          secondaryForeground: '#80B0D0',
          mutedForeground: '#5080A0',
        },
        secondary: '#1A2A3A',
        secondaryForeground: '#E0F0FF',
        muted: '#0A1A2A',
        mutedForeground: '#5080A0',
        border: '#2A3A4A',
        input: '#3A5A6A',
        ring: '#005A8A',
        primary: {
          default: '#005A8A',
          foreground: '#FFFFFF',
          hover: '#337AA3',
          light: '#003A5A',
          lightForeground: '#E0F0FF',
        },
        accent: {
          default: '#FFD700',
          foreground: '#0A1A2A',
          hover: '#FFE066',
          light: '#A0803A',
          lightForeground: '#E0F0FF',
        },
        success: {
          default: '#6CC470',
          foreground: '#0A1A2A',
          hover: '#4CAF50',
          light: '#3A7A3A',
          lightForeground: '#E0F0FF',
        },
        info: {
          default: '#64B5F6',
          foreground: '#0A1A2A',
          hover: '#2196F3',
          light: '#3A6A8A',
          lightForeground: '#E0F0FF',
        },
        warn: {
          default: '#FFD54F',
          foreground: '#0A1A2A',
          hover: '#FFC107',
          light: '#A0803A',
          lightForeground: '#E0F0FF',
        },
        danger: {
          default: '#EF9A9A',
          foreground: '#0A1A2A',
          hover: '#F44336',
          light: '#A05050',
          lightForeground: '#E0F0FF',
        },
        help: {
          default: '#B0BEC5',
          foreground: '#0A1A2A',
          hover: '#607D8B',
          light: '#5A6A7A',
          lightForeground: '#E0F0FF',
        },
        sidebar: {
          background: '#1A2A3A',
          foreground: '#E0F0FF',
          primary: '#005A8A',
          primaryForeground: '#FFFFFF',
          accent: '#FFD700',
          accentForeground: '#0A1A2A',
          border: '#2A3A4A',
          ring: '#005A8A',
        },
      },
    },
  },

  // =========================================================================
  // 10. Industrial Tech (Advanced Monochrome/Contrast)
  // =========================================================================
  {
    name: 'industrial-tech',
    colors: {
      light: {
        background: '#F0F0F0',
        foreground: '#1A1A1A',
        neutral: {
          base: '#D0D0D0',
          bg: '#F8F8F8',
          foreground: '#1A1A1A',
          secondaryForeground: '#505050',
          mutedForeground: '#707070',
        },
        secondary: '#E8E8E8',
        secondaryForeground: '#1A1A1A',
        muted: '#F5F5F5',
        mutedForeground: '#707070',
        border: '#D0D0D0',
        input: '#E0E0E0',
        ring: '#006AD5',
        primary: {
          default: '#006AD5',
          foreground: '#F8FAFC',
          hover: '#005AB8',
          light: '#3399FF',
          lightForeground: '#FFFFFF',
        },
        accent: {
          default: '#FF4500',
          foreground: '#111111',
          hover: '#E03E00',
          light: '#FF7033',
          lightForeground: '#FFFFFF',
        },
        success: {
          default: '#4CAF50',
          foreground: '#333333',
          hover: '#439B47',
          light: '#6CC470',
          lightForeground: '#FFFFFF',
        },
        info: {
          default: '#2196F3',
          foreground: '#111111',
          hover: '#1976D2',
          light: '#64B5F6',
          lightForeground: '#FFFFFF',
        },
        warn: {
          default: '#FFC107',
          foreground: '#1A1A1A',
          hover: '#E0A800',
          light: '#FFD54F',
          lightForeground: '#1A1A1A',
        },
        danger: {
          default: '#F44336',
          foreground: '#111111',
          hover: '#D32F2F',
          light: '#EF9A9A',
          lightForeground: '#FFFFFF',
        },
        help: {
          default: '#607D8B',
          foreground: '#000000',
          hover: '#455A64',
          light: '#B0BEC5',
          lightForeground: '#FFFFFF',
        },
        sidebar: {
          background: '#F0F0F0',
          foreground: '#1A1A1A',
          primary: '#0071EB',
          primaryForeground: '#FFFFFF',
          accent: '#FF4500',
          accentForeground: '#111111',
          border: '#D0D0D0',
          ring: '#007BFF',
        },
      },
      dark: {
        background: '#1A1A1A',
        foreground: '#F0F0F0',
        neutral: {
          base: '#404040',
          bg: '#2A2A2A',
          foreground: '#F0F0F0',
          secondaryForeground: '#B0B0B0',
          mutedForeground: '#808080',
        },
        secondary: '#2A2A2A',
        secondaryForeground: '#F0F0F0',
        muted: '#1A1A1A',
        mutedForeground: '#808080',
        border: '#404040',
        input: '#505050',
        ring: '#006AD5',
        primary: {
          default: '#006AD5',
          foreground: '#F8FAFC',
          hover: '#3399FF',
          light: '#004A80',
          lightForeground: '#F0F0F0',
        },
        accent: {
          default: '#FF4500',
          foreground: '#111111',
          hover: '#FF7033',
          light: '#A02A00',
          lightForeground: '#F0F0F0',
        },
        success: {
          default: '#6CC470',
          foreground: '#1A1A1A',
          hover: '#4CAF50',
          light: '#3A7A3A',
          lightForeground: '#F0F0F0',
        },
        info: {
          default: '#64B5F6',
          foreground: '#1A1A1A',
          hover: '#2196F3',
          light: '#3A6A8A',
          lightForeground: '#F0F0F0',
        },
        warn: {
          default: '#FFD54F',
          foreground: '#1A1A1A',
          hover: '#FFC107',
          light: '#A0803A',
          lightForeground: '#F0F0F0',
        },
        danger: {
          default: '#EF9A9A',
          foreground: '#1A1A1A',
          hover: '#F44336',
          light: '#A05050',
          lightForeground: '#F0F0F0',
        },
        help: {
          default: '#B0BEC5',
          foreground: '#1A1A1A',
          hover: '#607D8B',
          light: '#5A6A7A',
          lightForeground: '#F0F0F0',
        },
        sidebar: {
          background: '#2A2A2A',
          foreground: '#F0F0F0',
          primary: '#006AD5',
          primaryForeground: '#F8FAFC',
          accent: '#FF4500',
          accentForeground: '#111111',
          border: '#404040',
          ring: '#007BFF',
        },
      },
    },
  },
]

export const DEFAULT_THEME_NAME = 'soft-morandi-pastels'
export const DEFAULT_THEME_MODE = 'auto' as const

/**
 * ProForm ColorPicker 插件示例默认 hex（与 `DEFAULT_THEME_NAME` 下 light.primary.default 一致，避免示例散落任意色值）
 */
export const DEMO_COLOR_PICKER_DEFAULT_HEX = '#1c1d22' as const

/**
 * 获取预设的主色（用于 UI 展示，如配色选择小球）
 * 若定义了 colors.light/dark 则根据 isDark 取对应 primary.default，否则取 preset.primary
 */
export function getPresetPrimaryColor(preset: ThemePreset, isDark: boolean): string {
  const modeKey = isDark ? 'dark' : 'light'
  const primary = preset.colors?.[modeKey]?.primary?.default ?? preset.primary
  return primary ?? '#6b7280'
}

/** 主题切换过渡时长默认值 (ms) */
export const DEFAULT_TRANSITION_DURATION: ThemeTransitionDuration = 600

/** 过渡时长选项（主色色块从浅到深 + i18n labelKey）
 * swatchStyle 使用 CSS 变量，随当前主题主色变化 */
export const TRANSITION_DURATION_OPTIONS: {
  value: ThemeTransitionDuration
  swatchStyle: string
  labelKey: string
}[] = [
  {
    value: 400,
    swatchStyle: 'rgb(var(--primary-hover))',
    labelKey: 'settings.durationUltraFast',
  },
  { value: 600, swatchStyle: 'rgb(var(--primary))', labelKey: 'settings.durationFast' },
  {
    value: 800,
    swatchStyle: 'rgb(var(--primary) / 0.5)',
    labelKey: 'settings.durationComfortable',
  },
  {
    value: 1200,
    swatchStyle: 'rgb(var(--primary) / 0.3)',
    labelKey: 'settings.durationSlow',
  },
  {
    value: 1600,
    swatchStyle: 'rgb(var(--primary-light))',
    labelKey: 'settings.durationUltraSlow',
  },
]
