#!/usr/bin/env node
import { readJson, writeJson, writeText, exists } from './utils.mjs'

const adapterManifest = readJson('.ai/protocol/adapter-manifest.json')
const protocolVersion = readJson('.ai/protocol/version.json')
const policyVersion = readJson('.ai/governance/policies/version.json')
const topology = readJson('.ai/governance/policies/topology.json')
const release = readJson('.ai/governance/policies/release.json')
const api = readJson('.ai/governance/policies/api.json')
const orchestration = readJson('.ai/orchestration/manifest.json')
const ruleIndex = readJson('.ai/manifests/rule-index.json')
const skillRouting = readJson('.ai/manifests/skill-routing.json')

const orphanChecks = {
  docsGeneratedExists: exists('docs/generated'),
  orchestrationManifestExists: exists('.ai/orchestration/manifest.json'),
  protocolVersionExists: exists('.ai/protocol/version.json'),
}

const packageRelationships = Object.fromEntries(
  topology.packages.map(item => [item.name, item.allowedWorkspaceDependencies])
)
const packageResponsibilities = Object.fromEntries(
  topology.packages.map(item => [item.name, item.responsibility ?? 'governed workspace package'])
)
const packageCriticality = Object.fromEntries(
  topology.packages.map(item => [item.name, item.criticality])
)

const boundaryStatus = {
  dependencyDirection: 'contracts -> core -> apps',
  runtimeNeutralCore: 'validated by pnpm arch:runtime and pnpm arch:boundaries',
  deepImports: 'validated by dependency-cruiser and scripts/architecture/validate-boundaries.mjs',
  crossAppImports: 'forbidden',
  removedRuntimeImports: 'validated by dependency and runtime boundary checks',
  installDeterminism: 'validated by pnpm install --frozen-lockfile',
  publicApiSurface: 'generated by pnpm api:report',
  supplyChain: 'validated by pnpm supply:check',
}

const report = {
  schemaVersion: 1,
  generatedBy: 'scripts/governance/report.mjs',
  protocolVersion,
  policyVersion,
  adapters: Object.keys(adapterManifest.adapterGuides),
  repoDefaults: adapterManifest.repoDefaults,
  orchestrationRoles: orchestration.roles.map(role => role.id),
  ruleCount: ruleIndex.rules.length,
  routedSkillCount: skillRouting.routes.length,
  orphanChecks,
  packageRelationships,
  packageResponsibilities,
  packageCriticality,
  releaseTopology: release.releaseOrder,
  apiCompatibility: {
    snapshotDir: api.snapshotDir,
    failOnExportRemoval: api.breakingChangeRules.failOnExportRemoval,
    failOnSubpathRemoval: api.breakingChangeRules.failOnSubpathRemoval,
  },
  boundaryStatus,
}

function describePackageDependencies(item) {
  return item.allowedWorkspaceDependencies.length > 0
    ? `${item.name} -> ${item.allowedWorkspaceDependencies.join(', ')}`
    : `${item.name}: no declared workspace dependencies`
}

writeJson('.ai/generated/governance-report.json', report)
writeText('docs/generated/governance-report.md', `# Governance Report\n\n- Protocol version: ${protocolVersion.protocolVersion}\n- Policy version: ${policyVersion.policyVersion}\n- Manifest version: ${protocolVersion.manifestVersion}\n- Adapter version: ${protocolVersion.adapterVersion}\n- Governance version: ${protocolVersion.governanceVersion}\n- Adapters: ${Object.keys(adapterManifest.adapterGuides).join(', ')}\n- Orchestration roles: ${orchestration.roles.map(role => role.id).join(', ')}\n- Rule count: ${ruleIndex.rules.length}\n- Skill routes: ${skillRouting.routes.length}\n\n## Dependency Graph\n\n${topology.packages.map(item => `- ${describePackageDependencies(item)}`).join('\n')}\n\n## Package Responsibilities\n\n${topology.packages.map(item => `- ${item.name}: ${item.responsibility ?? 'governed workspace package'}`).join('\n')}\n\n## Package Criticality\n\n${topology.packages.map(item => `- ${item.name}: ${item.criticality}`).join('\n')}\n\n## Boundary Validation Status\n\n- Dependency direction: ${boundaryStatus.dependencyDirection}\n- Runtime neutrality: ${boundaryStatus.runtimeNeutralCore}\n- Deep imports: ${boundaryStatus.deepImports}\n- Cross-app imports: ${boundaryStatus.crossAppImports}\n- Removed runtime imports: ${boundaryStatus.removedRuntimeImports}\n\n## Public API Governance\n\n- API report command: pnpm api:report\n- API snapshot directory: ${api.snapshotDir}\n- Fail on export removal: ${api.breakingChangeRules.failOnExportRemoval}\n- Fail on subpath removal: ${api.breakingChangeRules.failOnSubpathRemoval}\n- Approved public package exports are explicit package.json exports only.\n\n## Release Governance\n\n- Version governance: ${release.versionGovernance}\n- Release order: ${release.releaseOrder.join(' -> ')}\n- Release gate: pnpm release:governance\n\n## Build Graph Topology\n\n- Orchestrator: Turbo\n- Topological order: ${release.releaseOrder.join(' -> ')}\n- Recommended validation commands: pnpm lint:check, pnpm test:run, pnpm type-check, pnpm build:ci, pnpm governance:gate, pnpm ci:prepare-internal, pnpm ci:smoke:packages, pnpm vercel:build\n\n## Supply Chain Governance\n\n- Frozen install: ${boundaryStatus.installDeterminism}\n- Lifecycle scripts: forbidden by pnpm supply:check\n- Supply check: ${boundaryStatus.supplyChain}\n- SBOM: docs/generated/sbom.json\n\n## Orphan Checks\n\n- docs/generated present: ${orphanChecks.docsGeneratedExists}\n- orchestration manifest present: ${orphanChecks.orchestrationManifestExists}\n- protocol version present: ${orphanChecks.protocolVersionExists}\n`)
