/**
 * 核心主题预设池 (全状态极致定制版 - The Ultimate 11)
 * * 核心设计理念：
 * 1. 彻底绕过引擎的自动计算，为每一个主题的 Light/Dark 模式显式指定所有状态色。
 * 2. WCAG 严格对比度：深色背景必配白字 (#ffffff)，亮色背景必配极深色字。
 * 3. 色相融合 (Hue Harmony)：状态色不再是干巴巴的纯红纯绿，而是根据主色调做了冷暖偏移。
 */
export const THEME_PRESETS: CompleteThemePreset[] = [
  // =========================================================================
  // 极夜黑 (Midnight Classic)
  // Primary #1c1d22 · Accent #d88e69 · Neutral #89817e
  // =========================================================================
  {
    name: 'midnight-classic',
    colors: {
      light: {
        background: '#ecebea',
        foreground: '#020617',
        neutral: {
          base: '#d2cfce',
          bg: '#f7f6f6',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#eae8e8',
        secondaryForeground: '#020617',
        muted: '#f3f2f2',
        mutedForeground: '#020617',
        border: '#d2cfce',
        input: '#c2bdbc',
        ring: '#d88e69',
        primary: {
          default: '#1c1d22',
          foreground: '#ffffff',
          hover: '#191a1e',
          light: '#393a3e',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#d88e69',
          foreground: '#020617',
          hover: '#be7d5c',
          light: '#db9b7b',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#498c5d',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3a80bf',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cb862b',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#bf4c4c',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#816bce',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#08080a',
          foreground: '#ffffff',
          primary: '#d88e69',
          primaryForeground: '#020617',
          accent: '#2e2f34',
          accentForeground: '#ffffff',
          border: '#474342',
          ring: '#d88e69',
        },
      },
      dark: {
        background: '#040505',
        foreground: '#ffffff',
        neutral: {
          base: '#45413f',
          bg: '#070809',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ffffff',
        },
        secondary: '#2c2928',
        secondaryForeground: '#ffffff',
        muted: '#211f1e',
        mutedForeground: '#ffffff',
        border: '#45413f',
        input: '#97908d',
        ring: '#d88e69',
        primary: {
          default: '#494a4e',
          foreground: '#ffffff',
          hover: '#5f6063',
          light: '#171819',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#d88e69',
          foreground: '#020617',
          hover: '#dd9c7b',
          light: '#3f2b21',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#18351a',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#153248',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#49390e',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#461b1a',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#322b4a',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#030303',
          foreground: '#ffffff',
          primary: '#d88e69',
          primaryForeground: '#020617',
          accent: '#493024',
          accentForeground: '#ffffff',
          border: '#343130',
          ring: '#d88e69',
        },
      },
    },
  },

  // =========================================================================
  // 焦糖大地 (Earth Caramel)
  // Primary #d88e69 · Accent #c07541 · Neutral #d0b6a1
  // =========================================================================
  {
    name: 'earth-caramel',
    colors: {
      light: {
        background: '#f7f3f0',
        foreground: '#020617',
        neutral: {
          base: '#ede3db',
          bg: '#fcfaf8',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#f7f2ee',
        secondaryForeground: '#020617',
        muted: '#faf8f6',
        mutedForeground: '#020617',
        border: '#ede3db',
        input: '#e7d9ce',
        ring: '#c07541',
        primary: {
          default: '#d88e69',
          foreground: '#020617',
          hover: '#be7d5c',
          light: '#dc9c7c',
          lightForeground: '#020617',
        },
        accent: {
          default: '#c07541',
          foreground: '#020617',
          hover: '#a96739',
          light: '#c8875a',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4b8e5e',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c81c0',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cd882c',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c14d4d',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#836cce',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#3c281d',
          foreground: '#ffffff',
          primary: '#c07541',
          primaryForeground: '#020617',
          accent: '#db9775',
          accentForeground: '#020617',
          border: '#6c5f54',
          ring: '#c07541',
        },
      },
      dark: {
        background: '#231711',
        foreground: '#ffffff',
        neutral: {
          base: '#685b51',
          bg: '#38251b',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#d0b6a1',
        },
        secondary: '#433a34',
        secondaryForeground: '#ffffff',
        muted: '#322c27',
        mutedForeground: '#d0b6a1',
        border: '#685b51',
        input: '#d6bfac',
        ring: '#c07541',
        primary: {
          default: '#d88e69',
          foreground: '#020617',
          hover: '#dd9c7b',
          light: '#56382a',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#c07541',
          foreground: '#020617',
          hover: '#c88658',
          light: '#4f311e',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#2e4223',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#2c3f51',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#5f4616',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#5c2823',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#483752',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#160e0a',
          foreground: '#ffffff',
          primary: '#c07541',
          primaryForeground: '#020617',
          accent: '#412816',
          accentForeground: '#ffffff',
          border: '#4f453d',
          ring: '#c07541',
        },
      },
    },
  },

  // =========================================================================
  // 奶昔象牙 (Ivory Cream)
  // Primary #e1d7cc · Accent #827265 · Neutral #ebe7e4
  // =========================================================================
  {
    name: 'ivory-cream',
    colors: {
      light: {
        background: '#fcfbfb',
        foreground: '#020617',
        neutral: {
          base: '#f7f6f5',
          bg: '#fefdfd',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#fbfbfa',
        secondaryForeground: '#020617',
        muted: '#fdfdfc',
        mutedForeground: '#020617',
        border: '#f7f6f5',
        input: '#f5f3f1',
        ring: '#827265',
        primary: {
          default: '#e1d7cc',
          foreground: '#020617',
          hover: '#c6bdb4',
          light: '#e5dcd3',
          lightForeground: '#020617',
        },
        accent: {
          default: '#827265',
          foreground: '#ffffff',
          hover: '#726459',
          light: '#93857a',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4c8f5f',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c83c1',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#ce892d',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c24e4e',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#846dd0',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#3f3c39',
          foreground: '#ffffff',
          primary: '#827265',
          primaryForeground: '#ffffff',
          accent: '#e3dad0',
          accentForeground: '#020617',
          border: '#7a7877',
          ring: '#827265',
        },
      },
      dark: {
        background: '#242221',
        foreground: '#ffffff',
        neutral: {
          base: '#767472',
          bg: '#3b3835',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ebe7e4',
        },
        secondary: '#4b4a49',
        secondaryForeground: '#ffffff',
        muted: '#383737',
        mutedForeground: '#ebe7e4',
        border: '#767472',
        input: '#edeae7',
        ring: '#827265',
        primary: {
          default: '#e1d7cc',
          foreground: '#020617',
          hover: '#e5dcd2',
          light: '#595551',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#827265',
          foreground: '#ffffff',
          hover: '#918377',
          light: '#3e3834',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#2f492e',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#2c475c',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#604e22',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#5d302e',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#493f5e',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#161514',
          foreground: '#ffffff',
          primary: '#827265',
          primaryForeground: '#ffffff',
          accent: '#2c2722',
          accentForeground: '#ffffff',
          border: '#595857',
          ring: '#827265',
        },
      },
    },
  },

  // =========================================================================
  // 陨石灰褐 (Stone Taupe)
  // Primary #827265 · Accent #d9d5d2 · Neutral #606062
  // =========================================================================
  {
    name: 'stone-taupe',
    colors: {
      light: {
        background: '#e6e6e6',
        foreground: '#020617',
        neutral: {
          base: '#c3c3c3',
          bg: '#f4f4f4',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#606062',
        },
        secondary: '#e2e2e3',
        secondaryForeground: '#020617',
        muted: '#efefef',
        mutedForeground: '#606062',
        border: '#c3c3c3',
        input: '#acacad',
        ring: '#d9d5d2',
        primary: {
          default: '#827265',
          foreground: '#ffffff',
          hover: '#726459',
          light: '#908277',
          lightForeground: '#020617',
        },
        accent: {
          default: '#d9d5d2',
          foreground: '#020617',
          hover: '#bfbbb9',
          light: '#dbd7d5',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#498c5c',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3980be',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#ca862b',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#be4b4b',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#816acd',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#24201c',
          foreground: '#ffffff',
          primary: '#d9d5d2',
          primaryForeground: '#020617',
          accent: '#8c7d71',
          accentForeground: '#020617',
          border: '#323233',
          ring: '#d9d5d2',
        },
      },
      dark: {
        background: '#151210',
        foreground: '#ffffff',
        neutral: {
          base: '#303031',
          bg: '#221e1a',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ffffff',
        },
        secondary: '#1f1f1f',
        secondaryForeground: '#ffffff',
        muted: '#171718',
        mutedForeground: '#ffffff',
        border: '#303031',
        input: '#737375',
        ring: '#d9d5d2',
        primary: {
          default: '#827265',
          foreground: '#ffffff',
          hover: '#918377',
          light: '#342d28',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#d9d5d2',
          foreground: '#020617',
          hover: '#dedad7',
          light: '#4c4946',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#243e22',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#223b50',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#554216',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#522422',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#3e3452',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#0d0b0a',
          foreground: '#ffffff',
          primary: '#d9d5d2',
          primaryForeground: '#020617',
          accent: '#4a4847',
          accentForeground: '#ffffff',
          border: '#242425',
          ring: '#d9d5d2',
        },
      },
    },
  },

  // =========================================================================
  // 深邃蓝宝石 (Sapphire Marine)
  // Primary #3c7b9f · Accent #69b5d7 · Neutral #434254
  // =========================================================================
  {
    name: 'sapphire-marine',
    colors: {
      light: {
        background: '#e1e1e4',
        foreground: '#020617',
        neutral: {
          base: '#b8b7be',
          bg: '#f2f2f3',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#434254',
        },
        secondary: '#dddde0',
        secondaryForeground: '#020617',
        muted: '#ececee',
        mutedForeground: '#434254',
        border: '#b8b7be',
        input: '#9d9da6',
        ring: '#69b5d7',
        primary: {
          default: '#3c7b9f',
          foreground: '#ffffff',
          hover: '#356c8c',
          light: '#5389a9',
          lightForeground: '#020617',
        },
        accent: {
          default: '#69b5d7',
          foreground: '#020617',
          hover: '#5c9fbd',
          light: '#7abbd9',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#488b5c',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#387fbe',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#ca852a',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#be4b4b',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#8069cd',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#11222d',
          foreground: '#ffffff',
          primary: '#69b5d7',
          primaryForeground: '#020617',
          accent: '#4c86a7',
          accentForeground: '#020617',
          border: '#23222c',
          ring: '#69b5d7',
        },
      },
      dark: {
        background: '#0a1419',
        foreground: '#ffffff',
        neutral: {
          base: '#22212a',
          bg: '#102029',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ffffff',
        },
        secondary: '#15151b',
        secondaryForeground: '#ffffff',
        muted: '#101014',
        mutedForeground: '#ffffff',
        border: '#22212a',
        input: '#5a5969',
        ring: '#69b5d7',
        primary: {
          default: '#3c7b9f',
          foreground: '#ffffff',
          hover: '#538bab',
          light: '#18313f',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#69b5d7',
          foreground: '#020617',
          hover: '#7bbedc',
          light: '#25414e',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#1c3f28',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#1a3d57',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#4d441c',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#4a2628',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#363558',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#060c10',
          foreground: '#ffffff',
          primary: '#69b5d7',
          primaryForeground: '#020617',
          accent: '#243e49',
          accentForeground: '#ffffff',
          border: '#191920',
          ring: '#69b5d7',
        },
      },
    },
  },

  // =========================================================================
  // 樱花柔粉 (Blossom Pink)
  // Primary #dfafbb · Accent #fe60ba · Neutral #d2b0a7
  // =========================================================================
  {
    name: 'blossom-pink',
    colors: {
      light: {
        background: '#f8f2f1',
        foreground: '#020617',
        neutral: {
          base: '#eee1de',
          bg: '#fcf9f9',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#f7f1ef',
        secondaryForeground: '#020617',
        muted: '#fbf7f6',
        mutedForeground: '#020617',
        border: '#eee1de',
        input: '#e8d6d1',
        ring: '#fe60ba',
        primary: {
          default: '#dfafbb',
          foreground: '#020617',
          hover: '#c49aa5',
          light: '#e3b8c3',
          lightForeground: '#020617',
        },
        accent: {
          default: '#fe60ba',
          foreground: '#020617',
          hover: '#e054a4',
          light: '#fd74c2',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4b8d5e',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c81c0',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cd872c',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c14d4d',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#836ccf',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#3e3134',
          foreground: '#ffffff',
          primary: '#fe60ba',
          primaryForeground: '#020617',
          accent: '#e2b5c0',
          accentForeground: '#020617',
          border: '#6d5c57',
          ring: '#fe60ba',
        },
      },
      dark: {
        background: '#241c1e',
        foreground: '#ffffff',
        neutral: {
          base: '#695854',
          bg: '#3a2e31',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#d2b0a7',
        },
        secondary: '#433835',
        secondaryForeground: '#ffffff',
        muted: '#322a28',
        mutedForeground: '#d2b0a7',
        border: '#695854',
        input: '#d7b9b2',
        ring: '#fe60ba',
        primary: {
          default: '#dfafbb',
          foreground: '#020617',
          hover: '#e3b9c3',
          light: '#58454a',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#fe60ba',
          foreground: '#020617',
          hover: '#fe73c2',
          light: '#612f4a',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#2f452c',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#2c425a',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#604a20',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#5d2b2c',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#493b5c',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#161113',
          foreground: '#ffffff',
          primary: '#fe60ba',
          primaryForeground: '#020617',
          accent: '#56213f',
          accentForeground: '#ffffff',
          border: '#50433f',
          ring: '#fe60ba',
        },
      },
    },
  },

  // =========================================================================
  // 经典燃橙 (Sunset Citrus)
  // Primary #f2782f · Accent #f05841 · Neutral #ad907a
  // =========================================================================
  {
    name: 'sunset-citrus',
    colors: {
      light: {
        background: '#f2edea',
        foreground: '#020617',
        neutral: {
          base: '#e0d5cc',
          bg: '#f9f7f6',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#f0ebe7',
        secondaryForeground: '#020617',
        muted: '#f7f4f2',
        mutedForeground: '#020617',
        border: '#e0d5cc',
        input: '#d4c5ba',
        ring: '#f05841',
        primary: {
          default: '#f2782f',
          foreground: '#020617',
          hover: '#d56a29',
          light: '#f28849',
          lightForeground: '#020617',
        },
        accent: {
          default: '#f05841',
          foreground: '#020617',
          hover: '#d34d39',
          light: '#f06d59',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4a8d5d',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3b81bf',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cc872b',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c04c4c',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#826bce',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#44220d',
          foreground: '#ffffff',
          primary: '#f05841',
          primaryForeground: '#020617',
          accent: '#f38340',
          accentForeground: '#020617',
          border: '#5a4b3f',
          ring: '#f05841',
        },
      },
      dark: {
        background: '#271308',
        foreground: '#ffffff',
        neutral: {
          base: '#57483d',
          bg: '#3f1f0c',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ad907a',
        },
        secondary: '#372e27',
        secondaryForeground: '#ffffff',
        muted: '#2a231d',
        mutedForeground: '#ad907a',
        border: '#57483d',
        input: '#b79d8a',
        ring: '#f05841',
        primary: {
          default: '#f2782f',
          foreground: '#020617',
          hover: '#f48848',
          light: '#602f13',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#f05841',
          foreground: '#020617',
          hover: '#f26c58',
          light: '#5f2618',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#313f1c',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#2f3c4a',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#624310',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#5f251c',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#4b354c',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#180c05',
          foreground: '#ffffff',
          primary: '#f05841',
          primaryForeground: '#020617',
          accent: '#521e16',
          accentForeground: '#ffffff',
          border: '#42372e',
          ring: '#f05841',
        },
      },
    },
  },

  // =========================================================================
  // 明媚骄阳 (Golden Mimosa)
  // Primary #f6dd7f · Accent #df8818 · Neutral #ebdfb5
  // =========================================================================
  {
    name: 'golden-mimosa',
    colors: {
      light: {
        background: '#fcfaf3',
        foreground: '#020617',
        neutral: {
          base: '#f7f3e3',
          bg: '#fefdfa',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#fbf9f2',
        secondaryForeground: '#020617',
        muted: '#fdfcf8',
        mutedForeground: '#020617',
        border: '#f7f3e3',
        input: '#f5eed9',
        ring: '#df8818',
        primary: {
          default: '#f6dd7f',
          foreground: '#020617',
          hover: '#d8c270',
          light: '#f7e18f',
          lightForeground: '#020617',
        },
        accent: {
          default: '#df8818',
          foreground: '#020617',
          hover: '#c47815',
          light: '#e39837',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4c8f5e',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c82c0',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#ce882c',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c24e4d',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#846dcf',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#453e24',
          foreground: '#ffffff',
          primary: '#df8818',
          primaryForeground: '#020617',
          accent: '#f7e089',
          accentForeground: '#020617',
          border: '#7a745e',
          ring: '#df8818',
        },
      },
      dark: {
        background: '#272314',
        foreground: '#ffffff',
        neutral: {
          base: '#76705b',
          bg: '#403921',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ebdfb5',
        },
        secondary: '#4b473a',
        secondaryForeground: '#ffffff',
        muted: '#38362b',
        mutedForeground: '#ebdfb5',
        border: '#76705b',
        input: '#ede3be',
        ring: '#df8818',
        primary: {
          default: '#f6dd7f',
          foreground: '#020617',
          hover: '#f7e18e',
          light: '#615732',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#df8818',
          foreground: '#020617',
          hover: '#e39634',
          light: '#5b3f15',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#314a25',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#2f4753',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#624f18',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#5f3025',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#4b4054',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#19160d',
          foreground: '#ffffff',
          primary: '#df8818',
          primaryForeground: '#020617',
          accent: '#4c2e08',
          accentForeground: '#ffffff',
          border: '#595545',
          ring: '#df8818',
        },
      },
    },
  },

  // =========================================================================
  // 复古深红 (Crimson Velvet)
  // Primary #a4384f · Accent #da3b3b · Neutral #decdb3
  // =========================================================================
  {
    name: 'crimson-velvet',
    colors: {
      light: {
        background: '#faf7f3',
        foreground: '#020617',
        neutral: {
          base: '#f2ece2',
          bg: '#fdfcfa',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#f9f6f1',
        secondaryForeground: '#020617',
        muted: '#fcfaf7',
        mutedForeground: '#020617',
        border: '#f2ece2',
        input: '#eee5d7',
        ring: '#d93a3a',
        primary: {
          default: '#a4384f',
          foreground: '#ffffff',
          hover: '#903146',
          light: '#b05366',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#d93a3a',
          foreground: '#ffffff',
          hover: '#c03434',
          light: '#de5555',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4b8e5e',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c82c0',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cd882c',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c14e4d',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#836dcf',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#2e1016',
          foreground: '#ffffff',
          primary: '#d93a3a',
          primaryForeground: '#ffffff',
          accent: '#ab485d',
          accentForeground: '#ffffff',
          border: '#736b5d',
          ring: '#d93a3a',
        },
      },
      dark: {
        background: '#1a090d',
        foreground: '#ffffff',
        neutral: {
          base: '#6f675a',
          bg: '#2b0f15',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#decdb3',
        },
        secondary: '#474239',
        secondaryForeground: '#ffffff',
        muted: '#35312b',
        mutedForeground: '#decdb3',
        border: '#6f675a',
        input: '#e2d3bc',
        ring: '#d93a3a',
        primary: {
          default: '#b66072',
          foreground: '#020617',
          hover: '#bf7383',
          light: '#462129',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#d93a3a',
          foreground: '#ffffff',
          hover: '#de5353',
          light: '#50171a',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#283720',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#25354e',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#593c13',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#561e20',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#412d4f',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#100608',
          foreground: '#ffffff',
          primary: '#d93a3a',
          primaryForeground: '#ffffff',
          accent: '#4a1414',
          accentForeground: '#ffffff',
          border: '#544e44',
          ring: '#d93a3a',
        },
      },
    },
  },

  // =========================================================================
  // 水晶海葵 (Amethyst Orchid)
  // Primary #a6588c · Accent #965da8 · Neutral #d9c7d4
  // =========================================================================
  {
    name: 'amethyst-orchid',
    colors: {
      light: {
        background: '#f9f6f8',
        foreground: '#020617',
        neutral: {
          base: '#f1eaef',
          bg: '#fcfbfc',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#f8f5f7',
        secondaryForeground: '#020617',
        muted: '#fbf9fb',
        mutedForeground: '#020617',
        border: '#f1eaef',
        input: '#ebe2e9',
        ring: '#965da8',
        primary: {
          default: '#a6588c',
          foreground: '#ffffff',
          hover: '#924d7b',
          light: '#b26e9b',
          lightForeground: '#020617',
        },
        accent: {
          default: '#965da8',
          foreground: '#ffffff',
          hover: '#845294',
          light: '#a472b3',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#4b8e5f',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3c82c1',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cd882d',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#c14d4e',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#836cd0',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#2e1927',
          foreground: '#ffffff',
          primary: '#965da8',
          primaryForeground: '#ffffff',
          accent: '#ad6595',
          accentForeground: '#020617',
          border: '#71676e',
          ring: '#965da8',
        },
      },
      dark: {
        background: '#1b0e16',
        foreground: '#ffffff',
        neutral: {
          base: '#6d646a',
          bg: '#2b1724',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#d9c7d4',
        },
        secondary: '#454044',
        secondaryForeground: '#ffffff',
        muted: '#343033',
        mutedForeground: '#d9c7d4',
        border: '#6d646a',
        input: '#deced9',
        ring: '#965da8',
        primary: {
          default: '#a6588c',
          foreground: '#ffffff',
          hover: '#b16c9a',
          light: '#422337',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#965da8',
          foreground: '#ffffff',
          hover: '#a370b2',
          light: '#3d243f',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#293b26',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#263854',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#5a401a',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#562126',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#423156',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#11090e',
          foreground: '#ffffff',
          primary: '#965da8',
          primaryForeground: '#ffffff',
          accent: '#332039',
          accentForeground: '#ffffff',
          border: '#524c51',
          ring: '#965da8',
        },
      },
    },
  },

  // =========================================================================
  // 翡翠秘境 (Emerald Forest)
  // Primary #2f5c4f · Accent #0da57c · Neutral #847659
  // =========================================================================
  {
    name: 'emerald-forest',
    colors: {
      light: {
        background: '#ebe9e4',
        foreground: '#020617',
        neutral: {
          base: '#d0cbc0',
          bg: '#f6f5f3',
          foreground: '#020617',
          secondaryForeground: '#020617',
          mutedForeground: '#020617',
        },
        secondary: '#e9e6e1',
        secondaryForeground: '#020617',
        muted: '#f3f1ee',
        mutedForeground: '#020617',
        border: '#d0cbc0',
        input: '#bfb8a9',
        ring: '#0da57c',
        primary: {
          default: '#2f5c4f',
          foreground: '#ffffff',
          hover: '#295146',
          light: '#497064',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#0da57c',
          foreground: '#020617',
          hover: '#0b916d',
          light: '#2caf8b',
          lightForeground: '#020617',
        },
        success: {
          default: '#2f7d46',
          foreground: '#ffffff',
          hover: '#296e3e',
          light: '#498c5c',
          lightForeground: '#020617',
        },
        info: {
          default: '#1d6fb8',
          foreground: '#ffffff',
          hover: '#1a62a2',
          light: '#3a80be',
          lightForeground: '#020617',
        },
        warn: {
          default: '#c6760c',
          foreground: '#020617',
          hover: '#ae680b',
          light: '#cb862a',
          lightForeground: '#020617',
        },
        danger: {
          default: '#b83232',
          foreground: '#ffffff',
          hover: '#a22c2c',
          light: '#bf4c4b',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#7056c9',
          foreground: '#ffffff',
          hover: '#634cb1',
          light: '#816bcd',
          lightForeground: '#020617',
        },
        sidebar: {
          background: '#0d1a16',
          foreground: '#ffffff',
          primary: '#0da57c',
          primaryForeground: '#020617',
          accent: '#40695d',
          accentForeground: '#ffffff',
          border: '#453d2e',
          ring: '#0da57c',
        },
      },
      dark: {
        background: '#080f0d',
        foreground: '#ffffff',
        neutral: {
          base: '#423b2d',
          bg: '#0c1815',
          foreground: '#ffffff',
          secondaryForeground: '#ffffff',
          mutedForeground: '#ffffff',
        },
        secondary: '#2a261c',
        secondaryForeground: '#ffffff',
        muted: '#201c15',
        mutedForeground: '#ffffff',
        border: '#423b2d',
        input: '#93866d',
        ring: '#0da57c',
        primary: {
          default: '#597d72',
          foreground: '#ffffff',
          hover: '#6d8d83',
          light: '#1f2e29',
          lightForeground: '#ffffff',
        },
        accent: {
          default: '#0da57c',
          foreground: '#020617',
          hover: '#2ab08c',
          light: '#09392c',
          lightForeground: '#ffffff',
        },
        success: {
          default: '#4caf50',
          foreground: '#020617',
          hover: '#61b965',
          light: '#1b3c20',
          lightForeground: '#ffffff',
        },
        info: {
          default: '#42a5f5',
          foreground: '#020617',
          hover: '#59b0f6',
          light: '#18394e',
          lightForeground: '#ffffff',
        },
        warn: {
          default: '#fbbf24',
          foreground: '#020617',
          hover: '#fbc73e',
          light: '#4c4013',
          lightForeground: '#ffffff',
        },
        danger: {
          default: '#ef5350',
          foreground: '#020617',
          hover: '#f16865',
          light: '#492220',
          lightForeground: '#ffffff',
        },
        help: {
          default: '#a78bfa',
          foreground: '#020617',
          hover: '#b299fb',
          light: '#35324f',
          lightForeground: '#ffffff',
        },
        sidebar: {
          background: '#050908',
          foreground: '#ffffff',
          primary: '#0da57c',
          primaryForeground: '#020617',
          accent: '#04382a',
          accentForeground: '#ffffff',
          border: '#322d22',
          ring: '#0da57c',
        },
      },
    },
  },
]

export const DEFAULT_THEME_NAME = 'midnight-classic'
export const DEFAULT_THEME_MODE = 'auto' as const

/**
 * ProForm ColorPicker 插件示例默认 hex（与 `DEFAULT_THEME_NAME` 下 light.primary.default 一致，避免示例散落任意色值）
 */
export const DEMO_COLOR_PICKER_DEFAULT_HEX = '#1c1d22' as const

/**
 * 获取预设的主色（用于 UI 展示，如配色选择小球）
 * 若定义了 colors.light/dark 则根据 isDark 取对应 primary.default，否则取 preset.primary
 */
export function getPresetPrimaryColor(preset: ThemePreset, isDark: boolean): string {
  const modeKey = isDark ? 'dark' : 'light'
  const primary = preset.colors?.[modeKey]?.primary?.default ?? preset.primary
  return primary ?? '#6b7280'
}

/** 主题切换过渡时长默认值 (ms) */
export const DEFAULT_TRANSITION_DURATION: ThemeTransitionDuration = 600

/** 过渡时长选项（主色色块从浅到深 + i18n labelKey）
 * swatchStyle 使用 CSS 变量，随当前主题主色变化 */
export const TRANSITION_DURATION_OPTIONS: {
  value: ThemeTransitionDuration
  swatchStyle: string
  labelKey: string
}[] = [
  {
    value: 400,
    swatchStyle: 'rgb(var(--primary-hover))',
    labelKey: 'settings.durationUltraFast',
  },
  { value: 600, swatchStyle: 'rgb(var(--primary))', labelKey: 'settings.durationFast' },
  {
    value: 800,
    swatchStyle: 'rgb(var(--primary) / 0.5)',
    labelKey: 'settings.durationComfortable',
  },
  {
    value: 1200,
    swatchStyle: 'rgb(var(--primary) / 0.3)',
    labelKey: 'settings.durationSlow',
  },
  {
    value: 1600,
    swatchStyle: 'rgb(var(--primary-light))',
    labelKey: 'settings.durationUltraSlow',
  },
]
