/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimateWrapper: typeof import('./../components/AnimateWrapper/AnimateWrapper.vue')['default']
    BodyCellRenderer: typeof import('./../components/DataTable/BodyCellRenderer.tsx')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CScrollbar: typeof import('./../components/CScrollbar/CScrollbar.vue')['default']
    DataTable: typeof import('./../components/DataTable/DataTable.vue')['default']
    DataTableV2: typeof import('./../components/DataTable/DataTableV2.vue')['default']
    DataTableV2Cell: typeof import('./../components/DataTable/DataTableV2Cell.tsx')['default']
    DefaultContentRenderer: typeof import('./../components/PrimeDialog/defaultContentRenderer.tsx')['default']
    DefaultRenderer: typeof import('./../components/SchemaForm/components/DefaultRenderer.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EmptyState: typeof import('./../components/EmptyState/EmptyState.vue')['default']
    FormItems: typeof import('./../components/SchemaForm/components/FormItems.tsx')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Icons: typeof import('./../components/Icons/Icons.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MessageContent: typeof import('./../components/PrimeDialog/MessageContent.tsx')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PrimeVueDialog: typeof import('./../components/PrimeDialog/PrimeVueDialog.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RenderFn: typeof import('./../components/DataTable/RenderFn.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./../components/SchemaForm/SchemaForm.vue')['default']
    SectionsRenderer: typeof import('./../components/SchemaForm/components/SectionsRenderer.vue')['default']
    StepNavigation: typeof import('./../components/SchemaForm/components/StepNavigation.vue')['default']
    StepsHeader: typeof import('./../components/SchemaForm/components/StepsHeader.vue')['default']
    StepsRenderer: typeof import('./../components/SchemaForm/components/StepsRenderer.vue')['default']
    UseEcharts: typeof import('./../components/UseEcharts/UseEcharts.vue')['default']
    WrappedAutoComplete: typeof import('./../components/SchemaForm/components/wrappers/WrappedAutoComplete.vue')['default']
    WrappedColorPicker: typeof import('./../components/SchemaForm/components/wrappers/WrappedColorPicker.vue')['default']
    WrappedDatePicker: typeof import('./../components/SchemaForm/components/wrappers/WrappedDatePicker.vue')['default']
    WrappedInputGroup: typeof import('./../components/SchemaForm/components/wrappers/WrappedInputGroup.vue')['default']
    WrappedRadioButton: typeof import('./../components/SchemaForm/components/wrappers/WrappedRadioButton.vue')['default']
    WrappedSlider: typeof import('./../components/SchemaForm/components/wrappers/WrappedSlider.vue')['default']
    WrappedTreeSelect: typeof import('./../components/SchemaForm/components/wrappers/WrappedTreeSelect.vue')['default']
  }
}
