import { describe, expect, it } from 'vitest'
import {
  approvedPrimeVueAppImportFiles,
  classifyPrimeVueBoundaryReference,
  extractPrimeVueReferences,
  isPrimeVueAdapterFile,
  isPrimeVueBuildResolverBoundaryFile,
  isPrimeVueGeneratedComponentRegistryFile,
  isPrimeVueModule,
  isVueUiInternalFile,
  primeVueBoundaryPolicy,
} from './primevue-boundary-policy.mjs'

describe('PrimeVue boundary policy', () => {
  it('recognizes raw PrimeVue modules', () => {
    expect(isPrimeVueModule('primevue')).toBe(true)
    expect(isPrimeVueModule('primevue/button')).toBe(true)
    expect(isPrimeVueModule('@primevue/core')).toBe(true)
    expect(isPrimeVueModule('@ccd/vue-ui')).toBe(false)
  })

  it('extracts static, side-effect, re-export, and dynamic PrimeVue references', () => {
    expect(
      extractPrimeVueReferences(`
        import 'primevue/resources/theme.css'
        import Button from 'primevue/button'
        export { default as Toast } from 'primevue/toast'
        const module = import('@primevue/auto-import-resolver')
      `)
    ).toEqual([
      { kind: 'side-effect-import', specifier: 'primevue/resources/theme.css' },
      { kind: 'import-from', specifier: 'primevue/button' },
      { kind: 'export-from', specifier: 'primevue/toast' },
      { kind: 'import-call', specifier: '@primevue/auto-import-resolver' },
    ])
  })

  it('keeps app raw PrimeVue imports on an exact empty allowlist', () => {
    expect([...approvedPrimeVueAppImportFiles]).toEqual([])
    expect(
      primeVueBoundaryPolicy.appBootstrapImports['apps/web-demo/src/plugins/modules/primevue.ts']
    ).toMatchObject({
      allowedPackageImports: ['@ccd/vue-primevue-adapter', '@ccd/vue-ui'],
      rawPrimeVueImports: 'forbidden',
    })
  })

  it('classifies governed build and generated app boundaries', () => {
    expect(isPrimeVueBuildResolverBoundaryFile('apps/web-demo/build/resolvers/primevue.ts')).toBe(
      true
    )
    expect(
      isPrimeVueGeneratedComponentRegistryFile(
        'apps/web-demo/src/types/components.d.ts',
        '/* Generated by unplugin-vue-components */'
      )
    ).toBe(true)
    expect(
      isPrimeVueGeneratedComponentRegistryFile(
        'apps/web-demo/src/types/components.d.ts',
        'hand authored'
      )
    ).toBe(false)
  })

  it('classifies package ownership boundaries', () => {
    expect(isVueUiInternalFile('packages/vue-ui/src/ProTable/ProTable.vue')).toBe(true)
    expect(isPrimeVueAdapterFile('packages/vue-primevue-adapter/src/index.ts')).toBe(true)
    expect(isPrimeVueAdapterFile('packages/vue-ui/src/index.ts')).toBe(false)
  })

  it('classifies forbidden direct app imports and allowed adapter imports', () => {
    const directAppImport = classifyPrimeVueBoundaryReference(
      'apps/web-demo/src/views/dashboard/index.vue',
      '',
      { kind: 'import-from', specifier: 'primevue/button' }
    )
    const adapterImport = classifyPrimeVueBoundaryReference(
      'packages/vue-primevue-adapter/src/index.ts',
      '',
      { kind: 'import-from', specifier: 'primevue/config' }
    )

    expect(directAppImport).toMatchObject({
      allowed: false,
      ruleId: 'primevue-direct-import-boundary',
    })
    expect(adapterImport).toMatchObject({ allowed: true, reason: 'adapter' })
  })

  it('blocks raw PrimeVue public re-exports from vue-ui while allowing internal composition', () => {
    expect(
      classifyPrimeVueBoundaryReference('packages/vue-ui/src/CcdPrimeControls/index.ts', '', {
        kind: 'import-from',
        specifier: 'primevue/button',
      })
    ).toMatchObject({ allowed: true, reason: 'vue-ui-internal' })
    expect(
      classifyPrimeVueBoundaryReference('packages/vue-ui/src/index.ts', '', {
        kind: 'export-from',
        specifier: 'primevue/button',
      })
    ).toMatchObject({
      allowed: false,
      ruleId: 'primevue-public-api-leak',
    })
  })
})
