/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    EmptyState: typeof import('@ccd/vue-ui')['EmptyState']
    Icons: typeof import('@ccd/vue-ui')['Icons']
    InputText: typeof import('primevue/inputtext')['default']
    ProForm: typeof import('@ccd/vue-ui')['ProForm']
    ProTable: typeof import('@ccd/vue-ui')['ProTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    UseEcharts: typeof import('@/adapters/charts/UseEcharts.vue')['default']
  }
}
