/** 由 build/plugins.ts generateIconListsPlugin 在构建时生成，请勿手改 */

export const LUCIDE_ICONS: string[] = [
  'i-lucide-home',
  'i-lucide-user',
  'i-lucide-settings',
  'i-lucide-search',
  'i-lucide-bell',
  'i-lucide-mail',
  'i-lucide-calendar',
  'i-lucide-check',
  'i-lucide-x',
  'i-lucide-plus',
  'i-lucide-info',
  'i-lucide-menu',
  'i-lucide-chevron-right',
  'i-lucide-trash-2',
  'i-lucide-edit',
  'i-lucide-download',
  'i-lucide-upload',
  'i-lucide-external-link',
  'i-lucide-refresh-cw',
  'i-lucide-lock',
]
export const MDI_ICONS: string[] = [
  'i-mdi-home',
  'i-mdi-account',
  'i-mdi-cog',
  'i-mdi-magnify',
  'i-mdi-bell',
  'i-mdi-email',
  'i-mdi-calendar',
  'i-mdi-check',
  'i-mdi-close',
  'i-mdi-plus',
  'i-mdi-information',
  'i-mdi-menu',
  'i-mdi-chevron-right',
  'i-mdi-delete',
  'i-mdi-pencil',
  'i-mdi-download',
  'i-mdi-upload',
  'i-mdi-open-in-new',
  'i-mdi-refresh',
  'i-mdi-lock',
]
export const LOGOS_ICONS: string[] = [
  'i-logos-vue',
  'i-logos-vitejs',
  'i-logos-unocss',
  'i-logos-typescript-icon',
  'i-logos-javascript',
  'i-logos-pinia',
  'i-logos-react',
  'i-logos-nextjs-icon',
  'i-logos-naiveui',
  'i-logos-ant-design',
  'i-logos-tailwindcss-icon',
  'i-logos-visual-studio-code',
  'i-logos-github-icon',
  'i-logos-google-icon',
  'i-logos-chrome',
]
export const CUSTOM_ICONS: string[] = ['i-custom:custom-juejin']
export const IS_LITE_MODE: boolean = true
